'use strict';

const extractCardNames = function (s) {
  s = s.replace(/\n/g, '');
  const re = /\s+/;
  const cardNames = Array();
  s.split(re).forEach((text) => {
    if (text === '') {
      return;
    }
    let result = text;
    const idx = text.indexOf('(');
    if (idx !== -1) {
      result = text.slice(0, idx);
    }
    cardNames.push(result);
  })
  return cardNames;
}

/*
Valuable `script` is generated by minifying `template` funciton below
using https://javascript-minifier.com
*/
const createScript = function (cardNames) {
  const cardNamesStr = `["${cardNames.join('","')}"]`;
  const script = `let targets=${cardNamesStr},cardsAll=document.getElementsByClassName("mini-card-template"),cardNamesAll=document.getElementsByClassName("full-card-name-container"),count=Math.min(cardsAll.length,cardNamesAll.length);for(let e=0;e<count;++e)targets.includes(cardNamesAll[e].innerText)&&cardsAll[e].click();`
  return script;
}

/*
Valuable `script` above in `createScript` function is generated by
minifying this funciton.
This function itself is not intended to be called directly.
*/
const template = function () {
  let targets = ["XX", "XX", "XX", "XX", "XX", "XX", "XX", "XX", "XX", "XX"];
  let cardsAll = document.getElementsByClassName('mini-card-template');
  let cardNamesAll = document.getElementsByClassName('full-card-name-container');
  let count = Math.min(cardsAll.length, cardNamesAll.length);
  for (let i = 0; i < count; ++i) {
    if (targets.includes(cardNamesAll[i].innerText)) {
      cardsAll[i].click();
    }
  }
}

const buttonExtractEvent = function () {
  const pasted = document.getElementById('pastedText').value;
  const cardNames = extractCardNames(pasted);
  const count = Math.min(10, cardNames.length);
  for (let i = 0; i < count; ++i) {
    const id = `cardName${i}`;
    document.getElementById(id).value = cardNames[i];
  }
  const script = createScript(cardNames);
  document.getElementById('resultScript').value = script;
}

const buttonCopyScriptEvent = function () {
  const script = document.getElementById('resultScript').value;
  navigator.clipboard.writeText(script);
}

const buttonExtract = document.getElementById('buttonExtract');
buttonExtract.addEventListener('click', e => { buttonExtractEvent(); }, false);
const buttonCopyScript = document.getElementById('buttonCopyScript');
buttonCopyScript.addEventListener('click', e => { buttonCopyScriptEvent(); }, false);
